package org.gingolph.gingmap;

import java.util.Set;

import org.tmapi.core.Locator;

public interface ConstructSupport{

  /**
   * A unique id accross the TopicMap.
   * 
   * Storing the id in the support allows it to be persisted and also to be written in the Json form of the construct (which is generated by the support, not the construct).
   * 
   * If the construct is new, or the implementation is not persistent, this id will have to be generated. This is currently done by the Construct (through its TopicMap) although it could be done in the support itself.
   * @return
   */
  String getId();

  /**
   * Sets the id.
   * 
   * This method is called when the id is generated by the Construct, or when 2 constructs are merged.
   * @param id
   */
  void setId(String id);
  
  void addItemIdentifier(Locator identifier);

  Set<Locator> getItemIdentifiers();

  void removeItemIdentifier(Locator identifier);
}
